var config = {
    authentication: 'anonymous',
    auto_login: true,
    auto_join_rooms: [
        'lobby@conference.' + location.hostname,
    ],
    play_sounds: true,
    sounds_path: "sounds/",
    notification_icon: "image.png",
    muc_domain: "conference." + location.hostname,
    domain_placeholder: location.hostname,
    registration_domain: location.hostname,
    locked_domain: location.hostname,
    whitelisted_plugins: ["webmeet"],
    bosh_service_url: 'https://' + location.host + '/http-bind/',
    websocket_url: 'wss://' + location.host + '/ws/',
    jid: location.hostname,
    notify_all_room_messages: true,
    auto_reconnect: true,
    allow_non_roster_messaging: true,
    view_mode: 'embedded',
    webmeet_invitation: 'Please join meeting in room ',
    webmeet_record: false,
    webmeet_record_audio: false,
    webmeet_record_video: false,
    webmeet_transcription: false,
    webmeet_captions: false,
    ofswitch: false,
    /*fastpath: {
        workgroup: 'demo@workgroup.' + location.hostname,
        form: "demo",
        robotImage: 'data:image/jpeg;base64,xxxxxxxxx',
        userImage: 'data:image/gif;base64,xxxxxxxxx',
    },*/
    uport: false
};